/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BillingCycle = IDL.Variant({
  'Quarterly' : IDL.Null,
  'Monthly' : IDL.Null,
  'Annual' : IDL.Null,
});
export const Category = IDL.Variant({
  'Productivity' : IDL.Null,
  'Health' : IDL.Null,
  'Entertainment' : IDL.Null,
  'Other' : IDL.Null,
  'Finance' : IDL.Null,
});
export const Paise = IDL.Nat;
export const SubscriptionInput = IDL.Record({
  'name' : IDL.Text,
  'billingCycle' : BillingCycle,
  'notes' : IDL.Opt(IDL.Text),
  'category' : Category,
  'price' : Paise,
  'nextPaymentDate' : IDL.Text,
  'logoEmoji' : IDL.Opt(IDL.Text),
});
export const SubscriptionId = IDL.Nat;
export const CategoryBreakdown = IDL.Record({
  'category' : Category,
  'totalMonthlyPaise' : Paise,
});
export const Timestamp = IDL.Int;
export const Subscription = IDL.Record({
  'id' : SubscriptionId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'billingCycle' : BillingCycle,
  'notes' : IDL.Opt(IDL.Text),
  'category' : Category,
  'price' : Paise,
  'nextPaymentDate' : IDL.Text,
  'logoEmoji' : IDL.Opt(IDL.Text),
});
export const OptimizationSuggestion = IDL.Record({
  'subscription' : Subscription,
  'potentialSaving' : Paise,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSubscription' : IDL.Func([SubscriptionInput], [SubscriptionId], []),
  'cancelSubscription' : IDL.Func([SubscriptionId], [IDL.Bool], []),
  'getCategoryBreakdown' : IDL.Func(
      [],
      [IDL.Vec(CategoryBreakdown)],
      ['query'],
    ),
  'getOnboardingComplete' : IDL.Func([], [IDL.Bool], ['query']),
  'getOptimizationSuggestions' : IDL.Func(
      [],
      [IDL.Vec(OptimizationSuggestion)],
      ['query'],
    ),
  'getSubscriptionById' : IDL.Func(
      [SubscriptionId],
      [IDL.Opt(Subscription)],
      ['query'],
    ),
  'getSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getTotalMonthlySpend' : IDL.Func([], [IDL.Nat], ['query']),
  'getUpcomingRenewals' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Subscription)],
      ['query'],
    ),
  'setOnboardingComplete' : IDL.Func([], [], []),
  'updateSubscription' : IDL.Func(
      [SubscriptionId, SubscriptionInput],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BillingCycle = IDL.Variant({
    'Quarterly' : IDL.Null,
    'Monthly' : IDL.Null,
    'Annual' : IDL.Null,
  });
  const Category = IDL.Variant({
    'Productivity' : IDL.Null,
    'Health' : IDL.Null,
    'Entertainment' : IDL.Null,
    'Other' : IDL.Null,
    'Finance' : IDL.Null,
  });
  const Paise = IDL.Nat;
  const SubscriptionInput = IDL.Record({
    'name' : IDL.Text,
    'billingCycle' : BillingCycle,
    'notes' : IDL.Opt(IDL.Text),
    'category' : Category,
    'price' : Paise,
    'nextPaymentDate' : IDL.Text,
    'logoEmoji' : IDL.Opt(IDL.Text),
  });
  const SubscriptionId = IDL.Nat;
  const CategoryBreakdown = IDL.Record({
    'category' : Category,
    'totalMonthlyPaise' : Paise,
  });
  const Timestamp = IDL.Int;
  const Subscription = IDL.Record({
    'id' : SubscriptionId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'billingCycle' : BillingCycle,
    'notes' : IDL.Opt(IDL.Text),
    'category' : Category,
    'price' : Paise,
    'nextPaymentDate' : IDL.Text,
    'logoEmoji' : IDL.Opt(IDL.Text),
  });
  const OptimizationSuggestion = IDL.Record({
    'subscription' : Subscription,
    'potentialSaving' : Paise,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    'addSubscription' : IDL.Func([SubscriptionInput], [SubscriptionId], []),
    'cancelSubscription' : IDL.Func([SubscriptionId], [IDL.Bool], []),
    'getCategoryBreakdown' : IDL.Func(
        [],
        [IDL.Vec(CategoryBreakdown)],
        ['query'],
      ),
    'getOnboardingComplete' : IDL.Func([], [IDL.Bool], ['query']),
    'getOptimizationSuggestions' : IDL.Func(
        [],
        [IDL.Vec(OptimizationSuggestion)],
        ['query'],
      ),
    'getSubscriptionById' : IDL.Func(
        [SubscriptionId],
        [IDL.Opt(Subscription)],
        ['query'],
      ),
    'getSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getTotalMonthlySpend' : IDL.Func([], [IDL.Nat], ['query']),
    'getUpcomingRenewals' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Subscription)],
        ['query'],
      ),
    'setOnboardingComplete' : IDL.Func([], [], []),
    'updateSubscription' : IDL.Func(
        [SubscriptionId, SubscriptionInput],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };