/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SubscriptionInput {
    name: string;
    billingCycle: BillingCycle;
    notes?: string;
    category: Category;
    price: Paise;
    nextPaymentDate: string;
    logoEmoji?: string;
}
export type SubscriptionId = bigint;
export type Timestamp = bigint;
export interface Subscription {
    id: SubscriptionId;
    name: string;
    createdAt: Timestamp;
    isActive: boolean;
    billingCycle: BillingCycle;
    notes?: string;
    category: Category;
    price: Paise;
    nextPaymentDate: string;
    logoEmoji?: string;
}
export type Paise = bigint;
export interface CategoryBreakdown {
    category: Category;
    totalMonthlyPaise: Paise;
}
export interface OptimizationSuggestion {
    subscription: Subscription;
    potentialSaving: Paise;
    reason: string;
}
export enum BillingCycle {
    Quarterly = "Quarterly",
    Monthly = "Monthly",
    Annual = "Annual"
}
export enum Category {
    Productivity = "Productivity",
    Health = "Health",
    Entertainment = "Entertainment",
    Other = "Other",
    Finance = "Finance"
}
export interface backendInterface {
    addSubscription(input: SubscriptionInput): Promise<SubscriptionId>;
    cancelSubscription(id: SubscriptionId): Promise<boolean>;
    getCategoryBreakdown(): Promise<Array<CategoryBreakdown>>;
    getOnboardingComplete(): Promise<boolean>;
    getOptimizationSuggestions(): Promise<Array<OptimizationSuggestion>>;
    getSubscriptionById(id: SubscriptionId): Promise<Subscription | null>;
    getSubscriptions(): Promise<Array<Subscription>>;
    getTotalMonthlySpend(): Promise<bigint>;
    getUpcomingRenewals(isoToday: string): Promise<Array<Subscription>>;
    setOnboardingComplete(): Promise<void>;
    updateSubscription(id: SubscriptionId, input: SubscriptionInput): Promise<boolean>;
}
import type { BillingCycle as _BillingCycle, Category as _Category, CategoryBreakdown as _CategoryBreakdown, OptimizationSuggestion as _OptimizationSuggestion, Paise as _Paise, Subscription as _Subscription, SubscriptionId as _SubscriptionId, SubscriptionInput as _SubscriptionInput, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSubscription(arg0: SubscriptionInput): Promise<SubscriptionId> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubscription(to_candid_SubscriptionInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubscription(to_candid_SubscriptionInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async cancelSubscription(arg0: SubscriptionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelSubscription(arg0);
            return result;
        }
    }
    async getCategoryBreakdown(): Promise<Array<CategoryBreakdown>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryBreakdown();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryBreakdown();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnboardingComplete(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnboardingComplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnboardingComplete();
            return result;
        }
    }
    async getOptimizationSuggestions(): Promise<Array<OptimizationSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOptimizationSuggestions();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOptimizationSuggestions();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionById(arg0: SubscriptionId): Promise<Subscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionById(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionById(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptions();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptions();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalMonthlySpend(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalMonthlySpend();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalMonthlySpend();
            return result;
        }
    }
    async getUpcomingRenewals(arg0: string): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingRenewals(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingRenewals(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async setOnboardingComplete(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOnboardingComplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOnboardingComplete();
            return result;
        }
    }
    async updateSubscription(arg0: SubscriptionId, arg1: SubscriptionInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscription(arg0, to_candid_SubscriptionInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscription(arg0, to_candid_SubscriptionInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BillingCycle_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillingCycle): BillingCycle {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_CategoryBreakdown_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryBreakdown): CategoryBreakdown {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_OptimizationSuggestion_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OptimizationSuggestion): OptimizationSuggestion {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subscription]): Subscription | null {
    return value.length === 0 ? null : from_candid_Subscription_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subscription: _Subscription;
    potentialSaving: _Paise;
    reason: string;
}): {
    subscription: Subscription;
    potentialSaving: Paise;
    reason: string;
} {
    return {
        subscription: from_candid_Subscription_n15(_uploadFile, _downloadFile, value.subscription),
        potentialSaving: value.potentialSaving,
        reason: value.reason
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SubscriptionId;
    name: string;
    createdAt: _Timestamp;
    isActive: boolean;
    billingCycle: _BillingCycle;
    notes: [] | [string];
    category: _Category;
    price: _Paise;
    nextPaymentDate: string;
    logoEmoji: [] | [string];
}): {
    id: SubscriptionId;
    name: string;
    createdAt: Timestamp;
    isActive: boolean;
    billingCycle: BillingCycle;
    notes?: string;
    category: Category;
    price: Paise;
    nextPaymentDate: string;
    logoEmoji?: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        isActive: value.isActive,
        billingCycle: from_candid_BillingCycle_n17(_uploadFile, _downloadFile, value.billingCycle),
        notes: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.notes)),
        category: from_candid_Category_n10(_uploadFile, _downloadFile, value.category),
        price: value.price,
        nextPaymentDate: value.nextPaymentDate,
        logoEmoji: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.logoEmoji))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category: _Category;
    totalMonthlyPaise: _Paise;
}): {
    category: Category;
    totalMonthlyPaise: Paise;
} {
    return {
        category: from_candid_Category_n10(_uploadFile, _downloadFile, value.category),
        totalMonthlyPaise: value.totalMonthlyPaise
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Productivity: null;
} | {
    Health: null;
} | {
    Entertainment: null;
} | {
    Other: null;
} | {
    Finance: null;
}): Category {
    return "Productivity" in value ? Category.Productivity : "Health" in value ? Category.Health : "Entertainment" in value ? Category.Entertainment : "Other" in value ? Category.Other : "Finance" in value ? Category.Finance : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Quarterly: null;
} | {
    Monthly: null;
} | {
    Annual: null;
}): BillingCycle {
    return "Quarterly" in value ? BillingCycle.Quarterly : "Monthly" in value ? BillingCycle.Monthly : "Annual" in value ? BillingCycle.Annual : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OptimizationSuggestion>): Array<OptimizationSuggestion> {
    return value.map((x)=>from_candid_OptimizationSuggestion_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subscription>): Array<Subscription> {
    return value.map((x)=>from_candid_Subscription_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CategoryBreakdown>): Array<CategoryBreakdown> {
    return value.map((x)=>from_candid_CategoryBreakdown_n8(_uploadFile, _downloadFile, x));
}
function to_candid_BillingCycle_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingCycle): _BillingCycle {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionInput): _SubscriptionInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    billingCycle: BillingCycle;
    notes?: string;
    category: Category;
    price: Paise;
    nextPaymentDate: string;
    logoEmoji?: string;
}): {
    name: string;
    billingCycle: _BillingCycle;
    notes: [] | [string];
    category: _Category;
    price: _Paise;
    nextPaymentDate: string;
    logoEmoji: [] | [string];
} {
    return {
        name: value.name,
        billingCycle: to_candid_BillingCycle_n3(_uploadFile, _downloadFile, value.billingCycle),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        category: to_candid_Category_n5(_uploadFile, _downloadFile, value.category),
        price: value.price,
        nextPaymentDate: value.nextPaymentDate,
        logoEmoji: value.logoEmoji ? candid_some(value.logoEmoji) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingCycle): {
    Quarterly: null;
} | {
    Monthly: null;
} | {
    Annual: null;
} {
    return value == BillingCycle.Quarterly ? {
        Quarterly: null
    } : value == BillingCycle.Monthly ? {
        Monthly: null
    } : value == BillingCycle.Annual ? {
        Annual: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Productivity: null;
} | {
    Health: null;
} | {
    Entertainment: null;
} | {
    Other: null;
} | {
    Finance: null;
} {
    return value == Category.Productivity ? {
        Productivity: null
    } : value == Category.Health ? {
        Health: null
    } : value == Category.Entertainment ? {
        Entertainment: null
    } : value == Category.Other ? {
        Other: null
    } : value == Category.Finance ? {
        Finance: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
